//
// Generated file, do not edit! Created by nedtool 5.5 from stack/phy/packet/Coordinate.msg.
//

#ifndef __COORDINATE_M_H
#define __COORDINATE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>stack/phy/packet/Coordinate.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Coordinate
 * {
 *     double x;
 *     double y;
 * }
 * </pre>
 */
class Coordinate : public ::omnetpp::cPacket
{
  protected:
    double x;
    double y;

  private:
    void copy(const Coordinate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Coordinate&);

  public:
    Coordinate(const char *name=nullptr, short kind=0);
    Coordinate(const Coordinate& other);
    virtual ~Coordinate();
    Coordinate& operator=(const Coordinate& other);
    virtual Coordinate *dup() const override {return new Coordinate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Coordinate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Coordinate& obj) {obj.parsimUnpack(b);}


#endif // ifndef __COORDINATE_M_H

