//
// Generated file, do not edit! Created by nedtool 5.5 from stack/mac/packet/AskCoordinate.msg.
//

#ifndef __ASKCOORDINATE_M_H
#define __ASKCOORDINATE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>stack/mac/packet/AskCoordinate.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet AskCoordinate
 * {
 * }
 * </pre>
 */
class AskCoordinate : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const AskCoordinate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AskCoordinate&);

  public:
    AskCoordinate(const char *name=nullptr, short kind=0);
    AskCoordinate(const AskCoordinate& other);
    virtual ~AskCoordinate();
    AskCoordinate& operator=(const AskCoordinate& other);
    virtual AskCoordinate *dup() const override {return new AskCoordinate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AskCoordinate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AskCoordinate& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ASKCOORDINATE_M_H

